# Generated by Django 5.0.1 on 2025-05-30 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_remove_about_us_web_image_welcometo_web_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingopen',
            name='flexipay_for_first',
        ),
    ]
