# Generated by Django 5.0.1 on 2025-06-17 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_remove_bookingopen_flexipay_for_first'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingopen',
            old_name='priceing',
            new_name='pricing',
        ),
        migrations.RenameField(
            model_name='setting',
            old_name='cuntact_no',
            new_name='contact_no',
        ),
    ]
