# Generated by Django 5.0.1 on 2025-06-17 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_rename_priceing_bookingopen_pricing_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amenities',
            old_name='icone',
            new_name='icon',
        ),
        migrations.RenameField(
            model_name='amenities',
            old_name='icone2',
            new_name='icon2',
        ),
        migrations.RenameField(
            model_name='bookingopen',
            old_name='landp_arcel',
            new_name='land_parcel',
        ),
        migrations.RenameField(
            model_name='unique_selling_proposition',
            old_name='icone',
            new_name='icon',
        ),
        migrations.RenameField(
            model_name='unique_selling_proposition',
            old_name='icone2',
            new_name='icon2',
        ),
        migrations.RenameField(
            model_name='welcometo',
            old_name='readmore',
            new_name='read_more',
        ),
    ]
